persons:
  "Alexander Weigl":
    link: "https://formal.iti.kit.edu/weigl"
  "Martin Fr채nzle":
    link: "https://uol.de/socps/personen/prof-dr-martin-fraenzle"
    image: "https://uol.de/f/2/_processed_/a/8/csm_2017_11_Martin_Fraenzle_2_742ee467bb.jpg"

  "Noah Abou El Wafa":
    mail: "noah.abouelwafa@kit.edu"
    link: "https://www.math.cmu.edu/~nabouelw/"
  "Wolfgang Ahrendt":
    mail: "ahrendt@chalmers.se"
    link: ""
  "Thomas Baar":
    mail: "thomas.baar@htw-berlin.de"
    link: ""
  "Joshua Bachmeier":
    mail: "j.bachmeier@fzi.de"
    link: ""
  "Bernhard Beckert":
    mail: "beckert@kit.edu"
    link: "https://formal.iti.kit.edu/beckert"
  "Tabea Bordis":
    mail: "tabea.bordis@kit.edu"
    link: ""
  "Marvin Brieger":
    mail: "marvin.brieger@sosy.ifi.lmu.de"
    link: ""
  "Richard Bubel":
    mail: "bubel@cs.tu-darmstadt.de"
    link: ""
  "Julia Butte":
    mail: "uegqr@student.kit.edu"
    link: ""
  "Stijn de Gouw":
    mail: "sdg@ou.nl"
    link: ""
  "Daniel Drodt":
    mail: "daniel.drodt@tu-darmstadt.de"
    link: ""
  "Henriette F채rber":
    mail: "henriette.faerber@student.kit.edu"
    link: ""
  "George Granberry":
    mail: "george.granberry@gmail.com"
    link: ""
  "Lukas Gr채tz":
    mail: "lukas.graetz@tu-darmstadt.de"
    link: ""
  "Reiner H채hnle":
    mail: "reiner.haehnle@tu-darmstadt.de"
    link: ""
  "Jonathan Hellwig":
    mail: "jonathan.hellwig@kit.edu"
    link: ""
  "Asmae Heydari Tabar":
    mail: "asmae.heydari-tabar@kit.edu"
    link: ""
  "Carlos Ignacio Isasa Martin":
    mail: "cisasa@ece.au.dk"
    link: ""
  "Aditi Kabra":
    mail: "akabra@andrew.cmu.edu"
    link: "https://aditink.github.io/"
  "Eduard Kamburjan":
    mail: "eduard@ifi.uio.no"
    link: ""
  "Philipp Kern":
    mail: "philipp.kern@kit.edu"
    link: "https://formal.iti.kit.edu/kern"
  "Michael Kirsten":
    mail: "kirsten@kit.edu"
    link: "https://formal.iti.kit.edu/kirsten"
  "Jonas Klamroth":
    mail: "klamroth@fzi.de"
    link: ""
  "Maximilian Kodetzki":
    mail: "maximilian.kodetzki@kit.edu"
    link: ""
  "Florian Lanzinger":
    mail: "lanzinger@kit.edu"
    link: "https://formal.iti.kit.edu/lanzinger"
  "Jonathan Laurent":
    mail: "jonathan.laurent@kit.edu"
    link: "https://www.cs.cmu.edu/~jlaurent/"
  "Debasmita Lohar":
    mail: "debasmita.lohar@kit.edu"
    link: "https://formal.iti.kit.edu/lohar"
  "Joscha Mennicken":
    mail: "uzuue@student.kit.edu"
    link: ""
  "Wojciech Mostowski":
    mail: "wojciech.mostowski@hh.se"
    link: ""
  "Joel Nyholm":
    mail: "joel.nyholm@hh.se"
    link: ""
  "Romain Pascual":
    mail: "romain.pascual@kit.edu"
    link: "https://formal.iti.kit.edu/pascual"
  "Wolfram Pfeifer":
    mail: "wolfram.pfeifer@kit.edu"
    link: "https://formal.iti.kit.edu/pfeifer"
  "Andre Platzer":
    mail: "platzer@kit.edu"
    link: "https://symbolaris.org"
  "Enguerrand Prebet":
    mail: "enguerrand.prebet@kit.edu"
    link: "https://enguerrandprebet.github.io/"
  "Long Qian":
    mail: "longq@andrew.cmu.edu"
    link: "https://longqianql.github.io/"
  "Marco Scaletta":
    mail: "scaletta@cs.tu-darmstadt.de"
    link: ""
  "Ina Schaefer":
    mail: "ina.schaefer@kit.edu"
    link: ""
  "Jonas Schiffl":
    mail: "jonas.schiffl@kit.edu"
    link: "https://formal.iti.kit.edu/schiffl"
  "Peter Schmitt":
    mail: "peter.schmitt@kit.edu"
    link: ""
  "Anna Schmitt":
    mail: "Anna.Schmitt@tu-darmstadt.de"
    link: ""
  "Guilherme Silva":
    mail: "alvares@chalmers.se"
    link: ""
  "Yong Kiam Tan":
    mail: "tanyongkiam@gmail.com"
    link: ""
  "Samuel Teuber":
    mail: "teuber@kit.edu"
    link: "https://formal.iti.kit.edu/teuber"
  "Shmuel Tyszberowicz":
    mail: "tyshbe@tau.ac.il"
    link: ""
  "Mattias Ulbrich":
    mail: "ulbrich@kit.edu"
    link: "https://formal.iti.kit.edu/ulbrich"
  "Adele Veschetti":
    mail: "adele.veschetti@tu-darmstadt.de"
    link: ""
  "Alexander Weigl":
    mail: "weigl@kit.edu"
    link: "https://formal.iti.kit.edu/weigl"
