persons:
  "Alexander Weigl":
    link: "https://formal.iti.kit.edu/weigl"
  "Martin Fränzle":
    link: "https://uol.de/socps/personen/prof-dr-martin-fraenzle"
    image: "https://uol.de/f/2/_processed_/a/8/csm_2017_11_Martin_Fraenzle_2_742ee467bb.jpg"

  "Noah Abou El Wafa":
    mail: "noah.abouelwafa@kit.edu"
    link: "https://www.math.cmu.edu/~nabouelw/"
  "Wolfgang Ahrendt":
    mail: "ahrendt@chalmers.se"
    link: "https://www.cse.chalmers.se/~ahrendt/"
  "Thomas Baar":
    mail: "thomas.baar@htw-berlin.de"
    link: "https://www.htw-berlin.de/hochschule/personen/person/?eid=8197"
  "Joshua Bachmeier":
    mail: "j.bachmeier@fzi.de"
    link: "https://www.fzi.de/team/joshua-bachmeier/"
  "Dirk Beyer":
    link: "https://www.sosy-lab.org/people/beyer/"
  "Bernhard Beckert":
    mail: "beckert@kit.edu"
    link: "https://formal.iti.kit.edu/beckert"
  "Tabea Bordis":
    mail: "tabea.bordis@kit.edu"
    link: "https://tva.kastel.kit.edu/english/team_bordis.php"
  "Marvin Brieger":
    mail: "marvin.brieger@sosy.ifi.lmu.de"
    link: "https://www.sosy-lab.org/people/brieger/"
  "Richard Bubel":
    mail: "bubel@cs.tu-darmstadt.de"
    link: "https://www.informatik.tu-darmstadt.de/se/gruppenmitglieder/groupmembers_detailseite_51008.en.jsp"
  "Julia Butte":
    mail: "uegqr@student.kit.edu"
    link: ""
  "Stijn de Gouw":
    mail: "sdg@ou.nl"
    link: "https://research.ou.nl/en/persons/stijn-de-gouw-2"
  "Daniel Drodt":
    mail: "daniel.drodt@tu-darmstadt.de"
    link: "https://www.informatik.tu-darmstadt.de/se/gruppenmitglieder/groupmembers_detailseite_132224.en.jsp"
  "Henriette Färber":
    mail: "henriette.faerber@student.kit.edu"
    link: ""
  "George Granberry":
    mail: "george.granberry@gmail.com"
    link: "https://www.chalmers.se/en/persons/georgegr/"
  "Lukas Grätz":
    mail: "lukas.graetz@tu-darmstadt.de"
    link: "https://www.informatik.tu-darmstadt.de/se/gruppenmitglieder/groupmembers_detailseite_96960.en.jsp"
  "Reiner Hähnle":
    mail: "reiner.haehnle@tu-darmstadt.de"
    link: "https://www.informatik.tu-darmstadt.de/se/gruppenmitglieder/groupmembers_detailseite_30784.en.jsp"
  "Jonathan Hellwig":
    mail: "jonathan.hellwig@kit.edu"
    link: ""
  "Asmae Heydari Tabar":
    mail: "asmae.heydari-tabar@kit.edu"
    link: "https://tva.kastel.kit.edu/english/team_tabar.php"
  "Carlos Ignacio Isasa Martin":
    mail: "cisasa@ece.au.dk"
    link: "https://www.au.dk/en/cisasa@ece.au.dk"
  "Aditi Kabra":
    mail: "akabra@andrew.cmu.edu"
    link: "https://aditink.github.io/"
  "Eduard Kamburjan":
    mail: "eduard@ifi.uio.no"
    link: "https://edkamb.github.io/"
  "Philipp Kern":
    mail: "philipp.kern@kit.edu"
    link: "https://formal.iti.kit.edu/kern"
  "Michael Kirsten":
    mail: "kirsten@kit.edu"
    link: "https://formal.iti.kit.edu/kirsten"
  "Jonas Klamroth":
    mail: "klamroth@fzi.de"
    link: "https://www.fzi.de/team/jonas-klamroth/"
  "Maximilian Kodetzki":
    mail: "maximilian.kodetzki@kit.edu"
    link: "https://tva.kastel.kit.edu/english/team_kodetzki.php"
  "Florian Lanzinger":
    mail: "lanzinger@kit.edu"
    link: "https://formal.iti.kit.edu/lanzinger"
  "Jonathan Laurent":
    mail: "jonathan.laurent@kit.edu"
    link: "https://www.cs.cmu.edu/~jlaurent/"
  "Debasmita Lohar":
    mail: "debasmita.lohar@kit.edu"
    link: "https://formal.iti.kit.edu/lohar"
  "Joscha Mennicken":
    mail: "uzuue@student.kit.edu"
    link: ""
  "Wojciech Mostowski":
    mail: "wojciech.mostowski@hh.se"
    link: "https://wiki.hh.se/ceres/index.php/Wojciech_Mostowski"
  "Joel Nyholm":
    mail: "joel.nyholm@hh.se"
    link: ""
  "Romain Pascual":
    mail: "romain.pascual@kit.edu"
    link: "https://formal.iti.kit.edu/pascual"
  "Wolfram Pfeifer":
    mail: "wolfram.pfeifer@kit.edu"
    link: "https://formal.iti.kit.edu/pfeifer"
  "André Platzer":
    mail: "platzer@kit.edu"
    link: "https://symbolaris.org"
  "Enguerrand Prebet":
    mail: "enguerrand.prebet@kit.edu"
    link: "https://enguerrandprebet.github.io/"
  "Long Qian":
    mail: "longq@andrew.cmu.edu"
    link: "https://longqianql.github.io/"
  "Marco Scaletta":
    mail: "scaletta@cs.tu-darmstadt.de"
    link: "https://www.informatik.tu-darmstadt.de/se/gruppenmitglieder/groupmembers_detailseite_109120.en.jsp"
  "Ina Schaefer":
    mail: "ina.schaefer@kit.edu"
    link: "https://tva.kastel.kit.edu/english/team_schaefer.php"
  "Jonas Schiffl":
    mail: "jonas.schiffl@kit.edu"
    link: "https://formal.iti.kit.edu/schiffl"
  "Peter Schmitt":
    mail: "peter.schmitt@kit.edu"
    link: "https://formal.kastel.kit.edu/schmitt"
  "Anna Schmitt":
    mail: "Anna.Schmitt@tu-darmstadt.de"
    link: "https://www.informatik.tu-darmstadt.de/se/gruppenmitglieder/groupmembers_detailseite_123072.en.jsp"
  "Guilherme Silva":
    mail: "alvares@chalmers.se"
    link: "https://www.chalmers.se/en/persons/alvares/"
  "Yong Kiam Tan":
    mail: "tanyongkiam@gmail.com"
    link: "https://tanyongkiam.github.io/"
  "Samuel Teuber":
    mail: "teuber@kit.edu"
    link: "https://formal.iti.kit.edu/teuber"
  "Shmuel Tyszberowicz":
    mail: "tyshbe@tau.ac.il"
    link: ""
  "Mattias Ulbrich":
    mail: "ulbrich@kit.edu"
    link: "https://formal.iti.kit.edu/ulbrich"
  "Adele Veschetti":
    mail: "adele.veschetti@tu-darmstadt.de"
    link: "https://www.informatik.tu-darmstadt.de/se/gruppenmitglieder/groupmembers_detailseite_129664.en.jsp"
  "Alexander Weigl":
    mail: "weigl@kit.edu"
    link: "https://formal.iti.kit.edu/weigl"
