name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ ubuntu-latest }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Render Pages
      run: python3 

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
            